{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "58790eb0-ea31-4937-8bbd-fea6c6053ce5",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np \n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "df = pd.read_csv('synthetic_real_estate_data.xls')\n",
    "\n",
    "df.head(1)\n",
    "\n",
    "df.shape\n",
    "\n",
    "df.duplicated().sum()\n",
    "\n",
    "df['Price'].plot(kind = 'box')\n",
    "plt.show()\n",
    "\n",
    "df[df['Price'] > 350000].max()\n",
    "\n",
    "Q1 = df['Price'].quantile(0.25)\n",
    "Q3 = df['Price'].quantile(0.75)\n",
    "IQR = Q3 - Q1\n",
    "lower_bound = Q1 - 1.5 * IQR\n",
    "upper_bound = Q3 + 1.5 * IQR\n",
    "df = df[(df['Price'] >= lower_bound) & (df['Price'] <= upper_bound)]\n",
    "print(f\"After: {df.shape[0]} rows\")\n",
    "\n",
    "df = df[df['Price'] >=0]\n",
    "df.shape\n",
    "\n",
    "df.to_csv('data_clean.csv', index=False)\n",
    "\n",
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "x = df.drop(columns=['Price']) \n",
    "y = df['Price']\n",
    "\n",
    "x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)\n",
    "\n",
    "x_train.shape\n",
    "\n",
    "y_test.shape\n",
    "\n",
    "x_train = x_train.values \n",
    "x_train\n",
    "\n",
    "x_test = x_test.values\n",
    "x_test\n",
    "\n",
    "y_train = y_train.values\n",
    "y_train\n",
    "\n",
    "y_test = y_test.values\n",
    "y_test\n",
    "\n",
    "from sklearn.linear_model import LinearRegression\n",
    "from sklearn.metrics import r2_score\n",
    "\n",
    "lr = LinearRegression()\n",
    "\n",
    "pr = lr.predict(x_test)\n",
    "\n",
    "r2_score(y_test, pr)\n",
    "\n",
    "A = lr.predict([[1748.357077, 1, 1, 43, 11.268221]])\n",
    "B = lr.predict([[1430.867849, 2, 1, 39, 8.342830]])\n",
    "C = lr.predict([[1823.844269, 1, 2, 29, 4.716948]])\n",
    "print(A)\n",
    "print(B)\n",
    "print(C)\n",
    "\n",
    "# Applying poly regression\n",
    "\n",
    "from sklearn.preprocessing import PolynomialFeatures\n",
    "\n",
    "poly = PolynomialFeatures(degree=3)\n",
    "X_poly = poly.fit_transform(x)\n",
    "lin2 = LinearRegression()\n",
    "lin2.fit(X_poly, y)\n",
    "\n",
    "X_test_poly = poly.transform(x_test)\n",
    "pr = lin2.predict(X_test_poly)\n",
    "r2 = r2_score(y_test, pr)\n",
    "r2\n",
    "\n",
    "a = lin2.predict(poly.transform([[1748.357077, 1, 1, 43, 11.268221]]))\n",
    "b = lin2.predict(poly.transform([[1430.867849, 2, 1, 39, 8.342830]]))\n",
    "c = lin2.predict(poly.transform([[1823.844269, 1, 2, 29, 4.716948]]))\n",
    "print(a)\n",
    "print(b)\n",
    "print(c)\n",
    "\n",
    "\n",
    "import pickle\n",
    "\n",
    "house_prediction = lin2 \n",
    "\n",
    "with open(\"model.pkl\", \"wb\") as file:\n",
    "    pickle.dump(house_prediction, file)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
